name: freelens-ollama-stack
services:
  freelens-ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freelens-ollama
    ports:
      - "9898:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped

volumes:
  ollama:
